module.exports = {
  AVATAR_ACHIEVEMENT: 'AVATAR_ACHIEVEMENT',
  CREATED_POST_1: 'CREATED_POST_1',
  CREATED_POST_3: 'CREATED_POST_3',
  CREATED_POST_5: 'CREATED_POST_5',
  LEFT_COMMENT_1: 'LEFT_COMMENT_1',
  LEFT_COMMENT_3: 'LEFT_COMMENT_3',
  LEFT_COMMENT_5: 'LEFT_COMMENT_5'
}